//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/7/25 20:00:15
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Internal;
using Microsoft.EntityFrameworkCore.Metadata;

namespace PersonalPMSModel
{

    public partial class PersonalPMSModel : DbContext
    {

        public PersonalPMSModel() :
            base()
        {
            OnCreated();
        }

        public PersonalPMSModel(DbContextOptions<PersonalPMSModel> options) :
            base(options)
        {
            OnCreated();
        }

        protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        {
            if (!optionsBuilder.IsConfigured ||
                (!optionsBuilder.Options.Extensions.OfType<RelationalOptionsExtension>().Any(ext => !string.IsNullOrEmpty(ext.ConnectionString) || ext.Connection != null) &&
                 !optionsBuilder.Options.Extensions.Any(ext => !(ext is RelationalOptionsExtension) && !(ext is CoreOptionsExtension))))
            {
                // 使用配置文件中的连接字符串，而不是硬编码
                // 如果Program.cs中已经配置了连接字符串，这里就不需要再配置
                // optionsBuilder.UseSqlServer(@"Data Source=.;Initial Catalog=PersonalPMS;Integrated Security=True;Persist Security Info=True;TrustServerCertificate=true");
            }
            CustomizeConfiguration(ref optionsBuilder);
            base.OnConfiguring(optionsBuilder);
        }

        partial void CustomizeConfiguration(ref DbContextOptionsBuilder optionsBuilder);

        public virtual DbSet<PMS项目明细报表> PMS项目明细报表s
        {
            get;
            set;
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            this.PMS项目明细报表Mapping(modelBuilder);
            this.CustomizePMS项目明细报表Mapping(modelBuilder);

            RelationshipsMapping(modelBuilder);
            CustomizeMapping(ref modelBuilder);
        }

        #region PMS项目明细报表 Mapping

        private void PMS项目明细报表Mapping(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<PMS项目明细报表>().ToTable(@"PMS项目明细报表", @"dbo");
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目编码).HasColumnName(@"项目编码").HasColumnType(@"varchar(20)").IsRequired().ValueGeneratedNever().HasMaxLength(20);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.序号).HasColumnName(@"序号").HasColumnType(@"int").IsRequired().ValueGeneratedOnAdd().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目名称).HasColumnName(@"项目名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.投资主体).HasColumnName(@"投资主体").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.一级专业名称).HasColumnName(@"一级专业名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.二级专业名称).HasColumnName(@"二级专业名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.三级专业名称).HasColumnName(@"三级专业名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.四级专业名称).HasColumnName(@"四级专业名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目集名称).HasColumnName(@"项目集名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.建设类型).HasColumnName(@"建设类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.建设单位).HasColumnName(@"建设单位").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.需求单位).HasColumnName(@"需求单位").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目年份).HasColumnName(@"项目年份").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.管理方式).HasColumnName(@"管理方式").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项模式).HasColumnName(@"立项模式").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目编码生成方式).HasColumnName(@"项目编码生成方式").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目管理颗粒度).HasColumnName(@"项目管理颗粒度").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目管理专业).HasColumnName(@"项目管理专业").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目类别).HasColumnName(@"项目类别").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目类型).HasColumnName(@"项目类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.资金来源).HasColumnName(@"资金来源").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.产品管理域).HasColumnName(@"产品管理域").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程实施流程模板).HasColumnName(@"工程实施流程模板").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目状态).HasColumnName(@"项目状态").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目取消终止失效时间).HasColumnName(@"项目取消终止失效时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目取消终止失效原因).HasColumnName(@"项目取消终止失效原因").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否迁移项目).HasColumnName(@"是否迁移项目").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否当年在建工程).HasColumnName(@"是否当年在建工程").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.资产属性).HasColumnName(@"资产属性").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否研发资本化项目).HasColumnName(@"是否研发资本化项目").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否研发相关PMS).HasColumnName(@"是否研发相关PMS").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否研发相关RMS).HasColumnName(@"是否研发相关RMS").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工期模板名称).HasColumnName(@"工期模板名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目阶段新).HasColumnName(@"项目阶段新").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当前环节).HasColumnName(@"当前环节").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.二级组织).HasColumnName(@"二级组织").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.任务数).HasColumnName(@"任务数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否总部备案).HasColumnName(@"是否总部备案").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否总部核准).HasColumnName(@"是否总部核准").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.ERP项目状态).HasColumnName(@"ERP项目状态").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.最后一次设计批复).HasColumnName(@"最后一次设计批复").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计模式).HasColumnName(@"设计模式").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.质监申报状态).HasColumnName(@"质监申报状态").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工备案状态).HasColumnName(@"竣工备案状态").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.需求提交完成时间).HasColumnName(@"需求提交完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.需求评审完成填报时间).HasColumnName(@"需求评审完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.需求评审完成时间).HasColumnName(@"需求评审完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目启动时间).HasColumnName(@"项目启动时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.建设方案评审完成填报时间).HasColumnName(@"建设方案评审完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.建设方案评审完成时间).HasColumnName(@"建设方案评审完成时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项可研委托完成填报时间).HasColumnName(@"立项可研委托完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项可研编制完成填报时间).HasColumnName(@"立项可研编制完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.可研编制完成时间).HasColumnName(@"可研编制完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项可研会审完成填报时间).HasColumnName(@"立项可研会审完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.可研会审完成时间).HasColumnName(@"可研会审完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.上会决策完成填报时间).HasColumnName(@"上会决策完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.上会决策通过时间).HasColumnName(@"上会决策通过时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目创建时间).HasColumnName(@"项目创建时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.决策名称).HasColumnName(@"决策名称").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次立项决策完成填报时间).HasColumnName(@"第一次立项决策完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项决策完成填报时间).HasColumnName(@"立项决策完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目可研委托完成填报时间).HasColumnName(@"项目可研委托完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目可研编制完成填报时间).HasColumnName(@"项目可研编制完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目可研会审完成填报时间).HasColumnName(@"项目可研会审完成填报时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次立项批复类型).HasColumnName(@"第一次立项批复类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次立项批复完成时间).HasColumnName(@"第一次立项批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当前立项批复类型).HasColumnName(@"当前立项批复类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当前立项批复完成时间).HasColumnName(@"当前立项批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项变更批复时间).HasColumnName(@"立项变更批复时间").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目移交发起时间).HasColumnName(@"项目移交发起时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目移交完成时间).HasColumnName(@"项目移交完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目交接完成时间).HasColumnName(@"项目交接完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目实施计划编制审批完成时间).HasColumnName(@"项目实施计划编制审批完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目实施计划调整审批完成时间).HasColumnName(@"项目实施计划调整审批完成时间").HasColumnType(@"date").ValueGeneratedNever();
            // 注意：以下字段在数据库中不存在，使用Ignore忽略它们
            modelBuilder.Entity<PMS项目明细报表>().Ignore(x => x.总体进度计划开工计划完成时间);
            modelBuilder.Entity<PMS项目明细报表>().Ignore(x => x.总体进度计划割接上线计划完成时间);
            modelBuilder.Entity<PMS项目明细报表>().Ignore(x => x.总体进度计划竣工验收计划完成时间);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计委托完成时间).HasColumnName(@"设计委托完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计派工完成时间).HasColumnName(@"设计派工完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计勘察完成时间).HasColumnName(@"设计勘察完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.上线投产时间).HasColumnName(@"上线投产时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划设计批复时间).HasColumnName(@"计划设计批复时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次设计会审完成时间).HasColumnName(@"第一次设计会审完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计会审完成时间).HasColumnName(@"设计会审完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复创建时间).HasColumnName(@"设计批复创建时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.前总设计批复完成时间).HasColumnName(@"前总设计批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.修正设计批复完成时间).HasColumnName(@"修正设计批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次设计批复类型).HasColumnName(@"第一次设计批复类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次设计批复完成时间).HasColumnName(@"第一次设计批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当前设计批复类型).HasColumnName(@"当前设计批复类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当前设计批复完成时间).HasColumnName(@"当前设计批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计变更批复时间).HasColumnName(@"设计变更批复时间").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复完成时间最后一次).HasColumnName(@"设计批复完成时间最后一次").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程交接完成时间).HasColumnName(@"工程交接完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工派工完成时间).HasColumnName(@"施工派工完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理派工完成时间).HasColumnName(@"监理派工完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理规划细则审批完成时间).HasColumnName(@"监理规划细则审批完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理规划总结审批完成时间).HasColumnName(@"监理规划总结审批完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工组织设计时间).HasColumnName(@"施工组织设计时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.质监申报开始填报时间).HasColumnName(@"质监申报开始填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.质监申报完成填报时间).HasColumnName(@"质监申报完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计交底完成时间).HasColumnName(@"设计交底完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划开工时间).HasColumnName(@"计划开工时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.开工启动完成时间).HasColumnName(@"开工启动完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.开工报告完成时间).HasColumnName(@"开工报告完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.开工报告完成填报时间).HasColumnName(@"开工报告完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.系统调测完成时间).HasColumnName(@"系统调测完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.质量安全检查完成时间).HasColumnName(@"质量安全检查完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工序质量反馈完成时间).HasColumnName(@"工序质量反馈完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划完工时间).HasColumnName(@"计划完工时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.完工报告完成时间).HasColumnName(@"完工报告完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.完工报告完成填报时间).HasColumnName(@"完工报告完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.验收测试完成时间).HasColumnName(@"验收测试完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划割接上线时间).HasColumnName(@"计划割接上线时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.割接上线交维完成时间).HasColumnName(@"割接上线交维完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.割接上线交维填报时间).HasColumnName(@"割接上线交维填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.试运行完成填报时间).HasColumnName(@"试运行完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工验收类型).HasColumnName(@"竣工验收类型").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工验收发起时间).HasColumnName(@"竣工验收发起时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工验收完成时间).HasColumnName(@"竣工验收完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划验收批复时间).HasColumnName(@"计划验收批复时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.验收批复完成时间).HasColumnName(@"验收批复完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工备案开始时间).HasColumnName(@"竣工备案开始时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工备案完成时间).HasColumnName(@"竣工备案完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工备案完成填报时间).HasColumnName(@"竣工备案完成填报时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否无需结算审计).HasColumnName(@"是否无需结算审计").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划结算申请时间).HasColumnName(@"计划结算申请时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.结算审计申请时间).HasColumnName(@"结算审计申请时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.结算审计完成时间).HasColumnName(@"结算审计完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.是否无需决算审计).HasColumnName(@"是否无需决算审计").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划决算申请时间).HasColumnName(@"计划决算申请时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.决算审计申请完成时间).HasColumnName(@"决算审计申请完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.决算审计完成时间).HasColumnName(@"决算审计完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目归档完成时间).HasColumnName(@"项目归档完成时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.PMS第一次项目关闭时间).HasColumnName(@"PMS第一次项目关闭时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.PMS项目关闭原因).HasColumnName(@"PMS项目关闭原因").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.ERP第一次项目关闭时间).HasColumnName(@"ERP第一次项目关闭时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.ERP项目关闭时间).HasColumnName(@"ERP项目关闭时间").HasColumnType(@"date").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目立项申请金额).HasColumnName(@"项目立项申请金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项决策金额).HasColumnName(@"立项决策金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目创建金额).HasColumnName(@"项目创建金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次立项批复金额).HasColumnName(@"第一次立项批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.最新立项批复金额).HasColumnName(@"最新立项批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项变更批复金额只统计变更).HasColumnName(@"立项变更批复金额只统计变更").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.方案审批通过金额).HasColumnName(@"方案审批通过金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目设计派单金额).HasColumnName(@"项目设计派单金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目施工派单金额).HasColumnName(@"项目施工派单金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目监理派单金额).HasColumnName(@"项目监理派单金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.变更前设计会审总金额).HasColumnName(@"变更前设计会审总金额").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计会审金额).HasColumnName(@"设计会审金额").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价设计费).HasColumnName(@"设计批复造价设计费").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价施工费).HasColumnName(@"设计批复造价施工费").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价监理费).HasColumnName(@"设计批复造价监理费").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价安全生产费).HasColumnName(@"设计批复造价安全生产费").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价设备费).HasColumnName(@"设计批复造价设备费").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价其他费).HasColumnName(@"设计批复造价其他费").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价甲供材料费).HasColumnName(@"设计批复造价甲供材料费").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价可研费).HasColumnName(@"设计批复造价可研费").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复造价总金额).HasColumnName(@"设计批复造价总金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.第一次设计批复金额).HasColumnName(@"第一次设计批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.初步设计批复金额).HasColumnName(@"初步设计批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工图设计批复金额).HasColumnName(@"施工图设计批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复金额).HasColumnName(@"设计批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计变更批复总金额只统计变更).HasColumnName(@"设计变更批复总金额只统计变更").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.现场签证申请总金额仅统计审批完成).HasColumnName(@"现场签证申请总金额仅统计审批完成").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.现场签证报告总金额仅统计审批完成).HasColumnName(@"现场签证报告总金额仅统计审批完成").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.订单金额).HasColumnName(@"订单金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计费订单金额PMS).HasColumnName(@"设计费订单金额PMS").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工费订单金额PMS).HasColumnName(@"施工费订单金额PMS").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理费订单金额PMS).HasColumnName(@"监理费订单金额PMS").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.订单接收金额).HasColumnName(@"订单接收金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.订单已报账已付款金额).HasColumnName(@"订单已报账已付款金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.订单已报账未付款金额).HasColumnName(@"订单已报账未付款金额").HasColumnType(@"decimal(18,6)").ValueGeneratedNever().HasPrecision(18, 6);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当年资本开支计划一季度).HasColumnName(@"当年资本开支计划一季度").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当年资本开支计划二季度).HasColumnName(@"当年资本开支计划二季度").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当年资本开支计划三季度).HasColumnName(@"当年资本开支计划三季度").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当年资本开支计划四季度).HasColumnName(@"当年资本开支计划四季度").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.下一年度资本开支结转).HasColumnName(@"下一年度资本开支结转").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当年资本开支金额).HasColumnName(@"当年资本开支金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.累计资本开支金额).HasColumnName(@"累计资本开支金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.当年转资金额).HasColumnName(@"当年转资金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.累计转资金额).HasColumnName(@"累计转资金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.验收批复金额).HasColumnName(@"验收批复金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计费送审金额).HasColumnName(@"设计费送审金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计费审定金额).HasColumnName(@"设计费审定金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工费送审金额).HasColumnName(@"施工费送审金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工费审定金额).HasColumnName(@"施工费审定金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理费送审金额).HasColumnName(@"监理费送审金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理费审定金额).HasColumnName(@"监理费审定金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.决算审定金额).HasColumnName(@"决算审定金额").HasColumnType(@"decimal(18,4)").ValueGeneratedNever().HasPrecision(18, 4);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项批复文号).HasColumnName(@"立项批复文号").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.立项变更批复文号).HasColumnName(@"立项变更批复文号").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计批复文号).HasColumnName(@"设计批复文号").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.质监受理号).HasColumnName(@"质监受理号").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.竣工验收批复文号).HasColumnName(@"竣工验收批复文号").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划项目经理).HasColumnName(@"计划项目经理").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.计划项目经理所属组织).HasColumnName(@"计划项目经理所属组织").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程管理经理主).HasColumnName(@"工程管理经理主").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程管理经理主所属二级组织).HasColumnName(@"工程管理经理主所属二级组织").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程管理经理主所属组织).HasColumnName(@"工程管理经理主所属组织").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程管理经理辅).HasColumnName(@"工程管理经理辅").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程实施经理主).HasColumnName(@"工程实施经理主").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            // 注意：数据库中不存在"工程实施经理主所属组织"字段，使用Ignore忽略它
            modelBuilder.Entity<PMS项目明细报表>().Ignore(x => x.工程实施经理主所属组织);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.工程实施经理辅).HasColumnName(@"工程实施经理辅").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.运维经理).HasColumnName(@"运维经理").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.采购经理).HasColumnName(@"采购经理").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.项目会计).HasColumnName(@"项目会计").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.累计立项变更次数).HasColumnName(@"累计立项变更次数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.累计设计变更次数).HasColumnName(@"累计设计变更次数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计会审通过任务数).HasColumnName(@"设计会审通过任务数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.开工完成任务数).HasColumnName(@"开工完成任务数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.开工率项目下的任务开工率).HasColumnName(@"开工率项目下的任务开工率").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.完工完成任务数).HasColumnName(@"完工完成任务数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.完工率项目下的任务完工率).HasColumnName(@"完工率项目下的任务完工率").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.割接上线交维完成任务数).HasColumnName(@"割接上线交维完成任务数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.割接完成率项目下的任务割接完成率).HasColumnName(@"割接完成率项目下的任务割接完成率").HasColumnType(@"decimal(18,8)").ValueGeneratedNever().HasPrecision(18, 8);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.应签章数).HasColumnName(@"应签章数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.已签章数).HasColumnName(@"已签章数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.应归档数).HasColumnName(@"应归档数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.已归档数).HasColumnName(@"已归档数").HasColumnType(@"int").ValueGeneratedNever().HasPrecision(10, 0);
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.施工单位).HasColumnName(@"施工单位").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.监理单位).HasColumnName(@"监理单位").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.设计单位).HasColumnName(@"设计单位").HasColumnType(@"nvarchar(max)").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().Property(x => x.最后更新时间).HasColumnName(@"最后更新时间").HasColumnType(@"datetime2").ValueGeneratedNever();
            modelBuilder.Entity<PMS项目明细报表>().HasKey(@"项目编码");
        }

        partial void CustomizePMS项目明细报表Mapping(ModelBuilder modelBuilder);

        #endregion

        private void RelationshipsMapping(ModelBuilder modelBuilder)
        {
        }

        partial void CustomizeMapping(ref ModelBuilder modelBuilder);

        public bool HasChanges()
        {
            return ChangeTracker.Entries().Any(e => e.State == Microsoft.EntityFrameworkCore.EntityState.Added || e.State == Microsoft.EntityFrameworkCore.EntityState.Modified || e.State == Microsoft.EntityFrameworkCore.EntityState.Deleted);
        }

        partial void OnCreated();
    }
}
