//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2025/7/25 20:00:15
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace PersonalPMSModel
{
    public partial class PMS项目明细报表 {

        public PMS项目明细报表()
        {
            项目编码 = "";
            项目名称 = "";
            投资主体 = "";
            一级专业名称 = "";
            二级专业名称 = "";
            三级专业名称 = "";
            四级专业名称 = "";
            项目集名称 = "";
            建设类型 = "";
            建设单位 = "";
            需求单位 = "";
            管理方式 = "";
            立项模式 = "";
            项目编码生成方式 = "";
            项目管理颗粒度 = "";
            项目管理专业 = "";
            项目类别 = "";
            项目类型 = "";
            资金来源 = "";
            产品管理域 = "";
            工程实施流程模板 = "";
            项目状态 = "";
            项目取消终止失效原因 = "";
            是否迁移项目 = "";
            是否当年在建工程 = "";
            资产属性 = "";
            是否研发资本化项目 = "";
            是否研发相关PMS = "";
            是否研发相关RMS = "";
            工期模板名称 = "";
            项目阶段新 = "";
            当前环节 = "";
            二级组织 = "";
            是否总部备案 = "";
            是否总部核准 = "";
            ERP项目状态 = "";
            最后一次设计批复 = "";
            设计模式 = "";
            质监申报状态 = "";
            竣工备案状态 = "";
            决策名称 = "";
            第一次立项批复类型 = "";
            当前立项批复类型 = "";
            立项变更批复时间 = "";
            第一次设计批复类型 = "";
            当前设计批复类型 = "";
            设计变更批复时间 = "";
            竣工验收类型 = "";
            是否无需结算审计 = "";
            是否无需决算审计 = "";
            PMS项目关闭原因 = "";
            立项批复文号 = "";
            立项变更批复文号 = "";
            设计批复文号 = "";
            质监受理号 = "";
            竣工验收批复文号 = "";
            计划项目经理 = "";
            计划项目经理所属组织 = "";
            工程管理经理主 = "";
            工程管理经理主所属二级组织 = "";
            工程管理经理主所属组织 = "";
            工程管理经理辅 = "";
            工程实施经理主 = "";
            工程实施经理主所属组织 = "";
            工程实施经理辅 = "";
            运维经理 = "";
            采购经理 = "";
            项目会计 = "";
            施工单位 = "";
            监理单位 = "";
            设计单位 = "";
            OnCreated();
        }

        public string 项目编码 { get; set; }

        public int 序号 { get; set; }

        public string 项目名称 { get; set; }

        public string 投资主体 { get; set; }

        public string 一级专业名称 { get; set; }

        public string 二级专业名称 { get; set; }

        public string 三级专业名称 { get; set; }

        public string 四级专业名称 { get; set; }

        public string 项目集名称 { get; set; }

        public string 建设类型 { get; set; }

        public string 建设单位 { get; set; }

        public string 需求单位 { get; set; }

        public int? 项目年份 { get; set; }

        public string 管理方式 { get; set; }

        public string 立项模式 { get; set; }

        public string 项目编码生成方式 { get; set; }

        public string 项目管理颗粒度 { get; set; }

        public string 项目管理专业 { get; set; }

        public string 项目类别 { get; set; }

        public string 项目类型 { get; set; }

        public string 资金来源 { get; set; }

        public string 产品管理域 { get; set; }

        public string 工程实施流程模板 { get; set; }

        public string 项目状态 { get; set; }

        public DateTime? 项目取消终止失效时间 { get; set; }

        public string 项目取消终止失效原因 { get; set; }

        public string 是否迁移项目 { get; set; }

        public string 是否当年在建工程 { get; set; }

        public string 资产属性 { get; set; }

        public string 是否研发资本化项目 { get; set; }

        public string 是否研发相关PMS { get; set; }

        public string 是否研发相关RMS { get; set; }

        public string 工期模板名称 { get; set; }

        public string 项目阶段新 { get; set; }

        public string 当前环节 { get; set; }

        public string 二级组织 { get; set; }

        public int? 任务数 { get; set; }

        public string 是否总部备案 { get; set; }

        public string 是否总部核准 { get; set; }

        public string ERP项目状态 { get; set; }

        public string 最后一次设计批复 { get; set; }

        public string 设计模式 { get; set; }

        public string 质监申报状态 { get; set; }

        public string 竣工备案状态 { get; set; }

        public DateTime? 需求提交完成时间 { get; set; }

        public DateTime? 需求评审完成填报时间 { get; set; }

        public DateTime? 需求评审完成时间 { get; set; }

        public DateTime? 项目启动时间 { get; set; }

        public DateTime? 建设方案评审完成填报时间 { get; set; }

        public DateTime? 建设方案评审完成时间 { get; set; }

        public DateTime? 立项可研委托完成填报时间 { get; set; }

        public DateTime? 立项可研编制完成填报时间 { get; set; }

        public DateTime? 可研编制完成时间 { get; set; }

        public DateTime? 立项可研会审完成填报时间 { get; set; }

        public DateTime? 可研会审完成时间 { get; set; }

        public DateTime? 上会决策完成填报时间 { get; set; }

        public DateTime? 上会决策通过时间 { get; set; }

        public DateTime? 项目创建时间 { get; set; }

        public string 决策名称 { get; set; }

        public DateTime? 第一次立项决策完成填报时间 { get; set; }

        public DateTime? 立项决策完成填报时间 { get; set; }

        public DateTime? 项目可研委托完成填报时间 { get; set; }

        public DateTime? 项目可研编制完成填报时间 { get; set; }

        public DateTime? 项目可研会审完成填报时间 { get; set; }

        public string 第一次立项批复类型 { get; set; }

        public DateTime? 第一次立项批复完成时间 { get; set; }

        public string 当前立项批复类型 { get; set; }

        public DateTime? 当前立项批复完成时间 { get; set; }

        public string 立项变更批复时间 { get; set; }

        public DateTime? 项目移交发起时间 { get; set; }

        public DateTime? 项目移交完成时间 { get; set; }

        public DateTime? 项目交接完成时间 { get; set; }

        public DateTime? 项目实施计划编制审批完成时间 { get; set; }

        public DateTime? 项目实施计划调整审批完成时间 { get; set; }

        public DateTime? 总体进度计划开工计划完成时间 { get; set; }

        public DateTime? 总体进度计划割接上线计划完成时间 { get; set; }

        public DateTime? 总体进度计划竣工验收计划完成时间 { get; set; }

        public DateTime? 设计委托完成时间 { get; set; }

        public DateTime? 设计派工完成时间 { get; set; }

        public DateTime? 设计勘察完成时间 { get; set; }

        public DateTime? 上线投产时间 { get; set; }

        public DateTime? 计划设计批复时间 { get; set; }

        public DateTime? 第一次设计会审完成时间 { get; set; }

        public DateTime? 设计会审完成时间 { get; set; }

        public DateTime? 设计批复创建时间 { get; set; }

        public DateTime? 前总设计批复完成时间 { get; set; }

        public DateTime? 修正设计批复完成时间 { get; set; }

        public string 第一次设计批复类型 { get; set; }

        public DateTime? 第一次设计批复完成时间 { get; set; }

        public string 当前设计批复类型 { get; set; }

        public DateTime? 当前设计批复完成时间 { get; set; }

        public string 设计变更批复时间 { get; set; }

        public DateTime? 设计批复完成时间最后一次 { get; set; }

        public DateTime? 工程交接完成时间 { get; set; }

        public DateTime? 施工派工完成时间 { get; set; }

        public DateTime? 监理派工完成时间 { get; set; }

        public DateTime? 监理规划细则审批完成时间 { get; set; }

        public DateTime? 监理规划总结审批完成时间 { get; set; }

        public DateTime? 施工组织设计时间 { get; set; }

        public DateTime? 质监申报开始填报时间 { get; set; }

        public DateTime? 质监申报完成填报时间 { get; set; }

        public DateTime? 设计交底完成时间 { get; set; }

        public DateTime? 计划开工时间 { get; set; }

        public DateTime? 开工启动完成时间 { get; set; }

        public DateTime? 开工报告完成时间 { get; set; }

        public DateTime? 开工报告完成填报时间 { get; set; }

        public DateTime? 系统调测完成时间 { get; set; }

        public DateTime? 质量安全检查完成时间 { get; set; }

        public DateTime? 工序质量反馈完成时间 { get; set; }

        public DateTime? 计划完工时间 { get; set; }

        public DateTime? 完工报告完成时间 { get; set; }

        public DateTime? 完工报告完成填报时间 { get; set; }

        public DateTime? 验收测试完成时间 { get; set; }

        public DateTime? 计划割接上线时间 { get; set; }

        public DateTime? 割接上线交维完成时间 { get; set; }

        public DateTime? 割接上线交维填报时间 { get; set; }

        public DateTime? 试运行完成填报时间 { get; set; }

        public string 竣工验收类型 { get; set; }

        public DateTime? 竣工验收发起时间 { get; set; }

        public DateTime? 竣工验收完成时间 { get; set; }

        public DateTime? 计划验收批复时间 { get; set; }

        public DateTime? 验收批复完成时间 { get; set; }

        public DateTime? 竣工备案开始时间 { get; set; }

        public DateTime? 竣工备案完成时间 { get; set; }

        public DateTime? 竣工备案完成填报时间 { get; set; }

        public string 是否无需结算审计 { get; set; }

        public DateTime? 计划结算申请时间 { get; set; }

        public DateTime? 结算审计申请时间 { get; set; }

        public DateTime? 结算审计完成时间 { get; set; }

        public string 是否无需决算审计 { get; set; }

        public DateTime? 计划决算申请时间 { get; set; }

        public DateTime? 决算审计申请完成时间 { get; set; }

        public DateTime? 决算审计完成时间 { get; set; }

        public DateTime? 项目归档完成时间 { get; set; }

        public DateTime? PMS第一次项目关闭时间 { get; set; }

        public string PMS项目关闭原因 { get; set; }

        public DateTime? ERP第一次项目关闭时间 { get; set; }

        public DateTime? ERP项目关闭时间 { get; set; }

        public decimal? 项目立项申请金额 { get; set; }

        public decimal? 立项决策金额 { get; set; }

        public decimal? 项目创建金额 { get; set; }

        public decimal? 第一次立项批复金额 { get; set; }

        public decimal? 最新立项批复金额 { get; set; }

        public decimal? 立项变更批复金额只统计变更 { get; set; }

        public decimal? 方案审批通过金额 { get; set; }

        public decimal? 项目设计派单金额 { get; set; }

        public decimal? 项目施工派单金额 { get; set; }

        public decimal? 项目监理派单金额 { get; set; }

        public decimal? 变更前设计会审总金额 { get; set; }

        public decimal? 设计会审金额 { get; set; }

        public decimal? 设计批复造价设计费 { get; set; }

        public decimal? 设计批复造价施工费 { get; set; }

        public decimal? 设计批复造价监理费 { get; set; }

        public decimal? 设计批复造价安全生产费 { get; set; }

        public decimal? 设计批复造价设备费 { get; set; }

        public decimal? 设计批复造价其他费 { get; set; }

        public decimal? 设计批复造价甲供材料费 { get; set; }

        public decimal? 设计批复造价可研费 { get; set; }

        public decimal? 设计批复造价总金额 { get; set; }

        public decimal? 第一次设计批复金额 { get; set; }

        public decimal? 初步设计批复金额 { get; set; }

        public decimal? 施工图设计批复金额 { get; set; }

        public decimal? 设计批复金额 { get; set; }

        public decimal? 设计变更批复总金额只统计变更 { get; set; }

        public decimal? 现场签证申请总金额仅统计审批完成 { get; set; }

        public decimal? 现场签证报告总金额仅统计审批完成 { get; set; }

        public decimal? 订单金额 { get; set; }

        public decimal? 设计费订单金额PMS { get; set; }

        public decimal? 施工费订单金额PMS { get; set; }

        public decimal? 监理费订单金额PMS { get; set; }

        public decimal? 订单接收金额 { get; set; }

        public decimal? 订单已报账已付款金额 { get; set; }

        public decimal? 订单已报账未付款金额 { get; set; }

        public decimal? 当年资本开支计划一季度 { get; set; }

        public decimal? 当年资本开支计划二季度 { get; set; }

        public decimal? 当年资本开支计划三季度 { get; set; }

        public decimal? 当年资本开支计划四季度 { get; set; }

        public decimal? 下一年度资本开支结转 { get; set; }

        public decimal? 当年资本开支金额 { get; set; }

        public decimal? 累计资本开支金额 { get; set; }

        public decimal? 当年转资金额 { get; set; }

        public decimal? 累计转资金额 { get; set; }

        public decimal? 验收批复金额 { get; set; }

        public decimal? 设计费送审金额 { get; set; }

        public decimal? 设计费审定金额 { get; set; }

        public decimal? 施工费送审金额 { get; set; }

        public decimal? 施工费审定金额 { get; set; }

        public decimal? 监理费送审金额 { get; set; }

        public decimal? 监理费审定金额 { get; set; }

        public decimal? 决算审定金额 { get; set; }

        public string 立项批复文号 { get; set; }

        public string 立项变更批复文号 { get; set; }

        public string 设计批复文号 { get; set; }

        public string 质监受理号 { get; set; }

        public string 竣工验收批复文号 { get; set; }

        public string 计划项目经理 { get; set; }

        public string 计划项目经理所属组织 { get; set; }

        public string 工程管理经理主 { get; set; }

        public string 工程管理经理主所属二级组织 { get; set; }

        public string 工程管理经理主所属组织 { get; set; }

        public string 工程管理经理辅 { get; set; }

        public string 工程实施经理主 { get; set; }

        public string 工程实施经理主所属组织 { get; set; }

        public string 工程实施经理辅 { get; set; }

        public string 运维经理 { get; set; }

        public string 采购经理 { get; set; }

        public string 项目会计 { get; set; }

        public int? 累计立项变更次数 { get; set; }

        public int? 累计设计变更次数 { get; set; }

        public int? 设计会审通过任务数 { get; set; }

        public int? 开工完成任务数 { get; set; }

        public decimal? 开工率项目下的任务开工率 { get; set; }

        public int? 完工完成任务数 { get; set; }

        public decimal? 完工率项目下的任务完工率 { get; set; }

        public int? 割接上线交维完成任务数 { get; set; }

        public decimal? 割接完成率项目下的任务割接完成率 { get; set; }

        public int? 应签章数 { get; set; }

        public int? 已签章数 { get; set; }

        public int? 应归档数 { get; set; }

        public int? 已归档数 { get; set; }

        public string 施工单位 { get; set; }

        public string 监理单位 { get; set; }

        public string 设计单位 { get; set; }

        public DateTime? 最后更新时间 { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
